/*
  Curated list of Indian Institutes of National Importance for seeding the Convex `universities` table.

  Primary sources consulted:
  - JoSAA 2026 participating institutes dropdown: https://josaa.admissions.nic.in/applicant/seatmatrix/seatmatrixinfo.aspx
  - Wikipedia "Indian Institutes of Technology": https://en.wikipedia.org/wiki/Indian_Institutes_of_Technology
  - Wikipedia "National Institutes of Technology": https://en.wikipedia.org/wiki/National_Institutes_of_Technology
  - Wikipedia "Indian Institutes of Information Technology": https://en.wikipedia.org/wiki/Indian_Institutes_of_Information_Technology
  - Ministry of Education, Technical Education (institution counts): https://www.education.gov.in/technical-education-1
  - IIIT Vadodara International Campus Diu: https://iiitvadodara.ac.in/page.php?slug=icdcampus

  Composition: 23 IITs, 31 NITs, 26 IIITs (80 records total).

  Note on the 26th IIIT:
  The official MoE/Wikipedia IIIT group contains 25 institutes (5 centrally funded + 20 PPP).
  JoSAA 2025/2026 recognises a 26th participating institute: the satellite campus of IIIT Vadodara at Diu
  ("Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)").
  It is a JoSAA/CSAB-listed Institute of National Importance and is administered by IIIT Vadodara.
  We therefore selected it over independent non-JoSAA IIITs such as IIIT Hyderabad or IIIT Bhubaneswar.
*/

type InstituteOfNationalImportance = {
  university_name: string;
  city?: string;
  state: string;
  website: string;
  category: "IIT" | "NIT" | "IIIT";
  established_year?: number;
};

export const INSTITUTES_OF_NATIONAL_IMPORTANCE: InstituteOfNationalImportance[] = [
  {
    university_name: "Indian Institute of Technology Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    website: "https://www.iitbbs.ac.in/",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology Bombay",
    city: "Mumbai",
    state: "Maharashtra",
    website: "https://www.iitb.ac.in",
    category: "IIT",
    established_year: 1958,
  },
  {
    university_name: "Indian Institute of Technology Mandi",
    city: "Mandi",
    state: "Himachal Pradesh",
    website: "https://www.iitmandi.ac.in",
    category: "IIT",
    established_year: 2009,
  },
  {
    university_name: "Indian Institute of Technology Delhi",
    city: "New Delhi",
    state: "Delhi",
    website: "https://home.iitd.ac.in",
    category: "IIT",
    established_year: 1961,
  },
  {
    university_name: "Indian Institute of Technology Indore",
    city: "Indore",
    state: "Madhya Pradesh",
    website: "https://www.iiti.ac.in",
    category: "IIT",
    established_year: 2009,
  },
  {
    university_name: "Indian Institute of Technology Kharagpur",
    city: "Kharagpur",
    state: "West Bengal",
    website: "https://www.iitkgp.ac.in",
    category: "IIT",
    established_year: 1951,
  },
  {
    university_name: "Indian Institute of Technology Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    website: "https://www.iith.ac.in",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology Jodhpur",
    city: "Jodhpur",
    state: "Rajasthan",
    website: "https://www.iitj.ac.in/",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology Kanpur",
    city: "Kanpur",
    state: "Uttar Pradesh",
    website: "https://www.iitk.ac.in",
    category: "IIT",
    established_year: 1959,
  },
  {
    university_name: "Indian Institute of Technology Madras",
    city: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.iitm.ac.in",
    category: "IIT",
    established_year: 1959,
  },
  {
    university_name: "Indian Institute of Technology Gandhinagar",
    city: "Gandhinagar",
    state: "Gujarat",
    website: "https://www.iitgn.ac.in/",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology Patna",
    city: "Patna",
    state: "Bihar",
    website: "https://www.iitp.ac.in/",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology Roorkee",
    city: "Roorkee",
    state: "Uttarakhand",
    website: "https://www.iitr.ac.in",
    category: "IIT",
    established_year: 1847,
  },
  {
    university_name: "Indian Institute of Technology (ISM) Dhanbad",
    city: "Dhanbad",
    state: "Jharkhand",
    website: "https://www.iitism.ac.in/",
    category: "IIT",
    established_year: 1926,
  },
  {
    university_name: "Indian Institute of Technology Ropar",
    city: "Rupnagar",
    state: "Punjab",
    website: "https://www.iitrpr.ac.in/",
    category: "IIT",
    established_year: 2008,
  },
  {
    university_name: "Indian Institute of Technology (BHU) Varanasi",
    city: "Varanasi",
    state: "Uttar Pradesh",
    website: "https://www.iitbhu.ac.in",
    category: "IIT",
    established_year: 1919,
  },
  {
    university_name: "Indian Institute of Technology Guwahati",
    city: "Guwahati",
    state: "Assam",
    website: "https://www.iitg.ac.in",
    category: "IIT",
    established_year: 1994,
  },
  {
    university_name: "Indian Institute of Technology Bhilai",
    city: "Bhilai",
    state: "Chhattisgarh",
    website: "https://www.iitbhilai.ac.in/",
    category: "IIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Technology Goa",
    city: "Farmagudi",
    state: "Goa",
    website: "https://iitgoa.ac.in/",
    category: "IIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Technology Palakkad",
    city: "Palakkad",
    state: "Kerala",
    website: "https://iitpkd.ac.in/",
    category: "IIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Technology Tirupati",
    city: "Tirupati",
    state: "Andhra Pradesh",
    website: "https://www.iittp.ac.in/",
    category: "IIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Technology Jammu",
    city: "Jammu",
    state: "Jammu and Kashmir",
    website: "https://www.iitjammu.ac.in/",
    category: "IIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Technology Dharwad",
    city: "Dharwad",
    state: "Karnataka",
    website: "https://www.iitdh.ac.in/",
    category: "IIT",
    established_year: 2016,
  },
  {
    university_name: "Dr. B.R. Ambedkar National Institute of Technology, Jalandhar",
    city: "Jalandhar",
    state: "Punjab",
    website: "https://www.nitj.ac.in/",
    category: "NIT",
    established_year: 1987,
  },
  {
    university_name: "Malaviya National Institute of Technology Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    website: "https://mnit.ac.in/",
    category: "NIT",
    established_year: 1963,
  },
  {
    university_name: "Maulana Azad National Institute of Technology Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    website: "https://www.manit.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "Motilal Nehru National Institute of Technology Allahabad",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    website: "https://www.mnnit.ac.in/",
    category: "NIT",
    established_year: 1961,
  },
  {
    university_name: "National Institute of Technology Agartala",
    city: "Agartala",
    state: "Tripura",
    website: "https://www.nita.ac.in/",
    category: "NIT",
    established_year: 1965,
  },
  {
    university_name: "National Institute of Technology Calicut",
    city: "Kozhikode",
    state: "Kerala",
    website: "https://www.nitc.ac.in/",
    category: "NIT",
    established_year: 1961,
  },
  {
    university_name: "National Institute of Technology Delhi",
    city: "New Delhi",
    state: "Delhi",
    website: "https://nitdelhi.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Durgapur",
    city: "Durgapur",
    state: "West Bengal",
    website: "https://nitdgp.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "National Institute of Technology Goa",
    city: "Cuncolim",
    state: "Goa",
    website: "https://www.nitgoa.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Hamirpur",
    city: "Hamirpur",
    state: "Himachal Pradesh",
    website: "https://nith.ac.in/",
    category: "NIT",
    established_year: 1986,
  },
  {
    university_name: "National Institute of Technology Karnataka, Surathkal",
    city: "Surathkal",
    state: "Karnataka",
    website: "https://www.nitk.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "National Institute of Technology Meghalaya",
    city: "Shillong",
    state: "Meghalaya",
    website: "https://www.nitm.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Nagaland",
    city: "Chümoukedima",
    state: "Nagaland",
    website: "https://www.nitnagaland.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Patna",
    city: "Patna",
    state: "Bihar",
    website: "https://www.nitp.ac.in/",
    category: "NIT",
    established_year: 1886,
  },
  {
    university_name: "National Institute of Technology Puducherry",
    city: "Karaikal",
    state: "Puducherry",
    website: "https://www.nitpy.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Raipur",
    city: "Raipur",
    state: "Chhattisgarh",
    website: "https://www.nitrr.ac.in/",
    category: "NIT",
    established_year: 1956,
  },
  {
    university_name: "National Institute of Technology Sikkim",
    city: "Ravangla",
    state: "Sikkim",
    website: "https://nitsikkim.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology Arunachal Pradesh",
    city: "Yupia",
    state: "Arunachal Pradesh",
    website: "https://www.nitap.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology, Jamshedpur",
    city: "Jamshedpur",
    state: "Jharkhand",
    website: "https://www.nitjsr.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "National Institute of Technology, Kurukshetra",
    city: "Kurukshetra",
    state: "Haryana",
    website: "https://nitkkr.ac.in/",
    category: "NIT",
    established_year: 1963,
  },
  {
    university_name: "National Institute of Technology, Manipur",
    city: "Imphal",
    state: "Manipur",
    website: "https://www.nitmanipur.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology, Mizoram",
    city: "Aizawl",
    state: "Mizoram",
    website: "https://www.nitmz.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology, Rourkela",
    city: "Rourkela",
    state: "Odisha",
    website: "https://www.nitrkl.ac.in/",
    category: "NIT",
    established_year: 1961,
  },
  {
    university_name: "National Institute of Technology, Silchar",
    city: "Silchar",
    state: "Assam",
    website: "https://www.nits.ac.in/",
    category: "NIT",
    established_year: 1967,
  },
  {
    university_name: "National Institute of Technology, Srinagar",
    city: "Srinagar",
    state: "Jammu and Kashmir",
    website: "https://nitsri.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "National Institute of Technology, Tiruchirappalli",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    website: "https://www.nitt.edu/",
    category: "NIT",
    established_year: 1964,
  },
  {
    university_name: "National Institute of Technology, Uttarakhand",
    city: "Srinagar",
    state: "Uttarakhand",
    website: "https://nituk.ac.in/",
    category: "NIT",
    established_year: 2010,
  },
  {
    university_name: "National Institute of Technology, Warangal",
    city: "Warangal",
    state: "Telangana",
    website: "https://www.nitw.ac.in/",
    category: "NIT",
    established_year: 1959,
  },
  {
    university_name: "Sardar Vallabhbhai National Institute of Technology, Surat",
    city: "Surat",
    state: "Gujarat",
    website: "https://www.svnit.ac.in/",
    category: "NIT",
    established_year: 1961,
  },
  {
    university_name: "Visvesvaraya National Institute of Technology, Nagpur",
    city: "Nagpur",
    state: "Maharashtra",
    website: "https://vnit.ac.in/",
    category: "NIT",
    established_year: 1960,
  },
  {
    university_name: "National Institute of Technology, Andhra Pradesh",
    city: "Tadepalligudem",
    state: "Andhra Pradesh",
    website: "https://nitandhra.ac.in/",
    category: "NIT",
    established_year: 2015,
  },
  {
    university_name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior",
    city: "Gwalior",
    state: "Madhya Pradesh",
    website: "https://www.iiitm.ac.in/",
    category: "IIIT",
    established_year: 1997,
  },
  {
    university_name: "Indian Institute of Information Technology, Allahabad",
    city: "Allahabad",
    state: "Uttar Pradesh",
    website: "https://www.iiita.ac.in/",
    category: "IIIT",
    established_year: 1999,
  },
  {
    university_name: "Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design and Manufacturing, Jabalpur",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    website: "https://www.iiitdmj.ac.in/",
    category: "IIIT",
    established_year: 2005,
  },
  {
    university_name: "Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram",
    city: "Kancheepuram",
    state: "Tamil Nadu",
    website: "https://www.iiitdm.ac.in/",
    category: "IIIT",
    established_year: 2007,
  },
  {
    university_name: "Indian Institute of Information Technology, Design and Manufacturing, Kurnool",
    city: "Kurnool",
    state: "Andhra Pradesh",
    website: "https://www.iiitdmkl.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Sri City",
    city: "Sri City",
    state: "Andhra Pradesh",
    website: "https://www.iiits.ac.in/",
    category: "IIIT",
    established_year: 2013,
  },
  {
    university_name: "Indian Institute of Information Technology, Guwahati",
    city: "Guwahati",
    state: "Assam",
    website: "https://www.iiitg.ac.in/",
    category: "IIIT",
    established_year: 2013,
  },
  {
    university_name: "Indian Institute of Information Technology, Vadodara",
    city: "Gandhinagar",
    state: "Gujarat",
    website: "https://www.iiitvadodara.ac.in/",
    category: "IIIT",
    established_year: 2013,
  },
  {
    university_name: "Indian Institute of Information Technology, Kota",
    city: "Kota",
    state: "Rajasthan",
    website: "https://www.iiitkota.ac.in/",
    category: "IIIT",
    established_year: 2013,
  },
  {
    university_name: "Indian Institute of Information Technology, Tiruchirappalli",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    website: "https://www.iiitt.ac.in/",
    category: "IIIT",
    established_year: 2013,
  },
  {
    university_name: "Indian Institute of Information Technology, Dharwad",
    city: "Dharwad",
    state: "Karnataka",
    website: "https://www.iiitdwd.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Una",
    city: "Una",
    state: "Himachal Pradesh",
    website: "https://www.iiitu.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Sonepat",
    city: "Sonepat",
    state: "Haryana",
    website: "https://iiitsonepat.ac.in/",
    category: "IIIT",
    established_year: 2014,
  },
  {
    university_name: "Indian Institute of Information Technology, Kalyani",
    city: "Kalyani",
    state: "West Bengal",
    website: "https://www.iiitkalyani.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    website: "https://www.iiitl.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Kottayam",
    city: "Kottayam",
    state: "Kerala",
    website: "https://iiitkottayam.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Manipur",
    city: "Imphal",
    state: "Manipur",
    website: "https://iiitmanipur.ac.in/",
    category: "IIIT",
    established_year: 2015,
  },
  {
    university_name: "Indian Institute of Information Technology, Nagpur",
    city: "Nagpur",
    state: "Maharashtra",
    website: "https://iiitn.ac.in/",
    category: "IIIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Information Technology, Pune",
    city: "Pune",
    state: "Maharashtra",
    website: "https://iiitp.ac.in/",
    category: "IIIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Information Technology, Ranchi",
    city: "Ranchi",
    state: "Jharkhand",
    website: "https://iiitranchi.ac.in/",
    category: "IIIT",
    established_year: 2016,
  },
  {
    university_name: "Indian Institute of Information Technology, Bhagalpur",
    city: "Bhagalpur",
    state: "Bihar",
    website: "https://www.iiitbh.ac.in/",
    category: "IIIT",
    established_year: 2017,
  },
  {
    university_name: "Indian Institute of Information Technology, Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    website: "https://iiitbhopal.ac.in/",
    category: "IIIT",
    established_year: 2017,
  },
  {
    university_name: "Indian Institute of Information Technology, Surat",
    city: "Surat",
    state: "Gujarat",
    website: "https://iiitsurat.ac.in/",
    category: "IIIT",
    established_year: 2017,
  },
  {
    university_name: "Indian Institute of Information Technology, Agartala",
    city: "Agartala",
    state: "Tripura",
    website: "https://www.iiitagartala.ac.in/",
    category: "IIIT",
    established_year: 2018,
  },
  {
    university_name: "Indian Institute of Information Technology, Raichur",
    city: "Raichur",
    state: "Karnataka",
    website: "https://iiitr.ac.in/",
    category: "IIIT",
    established_year: 2019,
  },
  {
    university_name: "Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)",
    city: "Diu",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    website: "https://diu.iiitvadodara.ac.in/",
    category: "IIIT",
    established_year: 2020,
  }
];
